version: '3'

services:
  rabbit_mq: 
    container_name: rabbit
    build: 
      context: ./rabbit-mq
      dockerfile: ./Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
    restart: always